package com.readeveryday.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.readeveryday.greendao.MyCollect;

import com.readeveryday.greendao.MyCollectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCollectDaoConfig;

    private final MyCollectDao myCollectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCollectDaoConfig = daoConfigMap.get(MyCollectDao.class).clone();
        myCollectDaoConfig.initIdentityScope(type);

        myCollectDao = new MyCollectDao(myCollectDaoConfig, this);

        registerDao(MyCollect.class, myCollectDao);
    }
    
    public void clear() {
        myCollectDaoConfig.clearIdentityScope();
    }

    public MyCollectDao getMyCollectDao() {
        return myCollectDao;
    }

}
