package com.readeveryday.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.readeveryday.greendao.MyCollect;
import com.readeveryday.greendao.UserInfo;

import com.readeveryday.greendao.MyCollectDao;
import com.readeveryday.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCollectDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final MyCollectDao myCollectDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCollectDaoConfig = daoConfigMap.get(MyCollectDao.class).clone();
        myCollectDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        myCollectDao = new MyCollectDao(myCollectDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(MyCollect.class, myCollectDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        myCollectDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public MyCollectDao getMyCollectDao() {
        return myCollectDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
